### ISSUE TITLE
game crashing on launch

### ISSUE THREAD

**Issue by TrulyFooly** [deviant-dev/dominatrix-simulator-issues#185]
When I go to launch the game weather I launch it from in vr, in steam, in steam vr, it crashes. it recently started. it starts loading and sometimes it would show the picture of where I was at before and just crash. I tried restarting my computer, deleting and redownloading it and nothing worked

**Comment by ThatCuteEevee** [comment]
Hi @TrulyFooly, Thank you for taking the time to let us know about this. There is a separate report on this issue but are unable to replicate it ourselves. Could you provide system specs as well as the log files?

To get your log file, press Win+R and enter %USERPROFILE%/AppData/LocalLow/deviant.tech/Dominatrix Simulator\

Inside you'll find 'Player.log'

Send that file to support@deviant.tech, so we can look into what's specifically happening for you.

Edits: Added labels. Added Help Wanted due to this being a high piority issue being reported by another player:
 - https://steamcommunity.com/app/953270/discussions/0/3075377162311105677/

**Comment by TrulyFooly** [comment]
Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/Dominatrix
Simulator/Dominatrix Simulator_Data/Managed'
Mono config path = 'C:/Program Files
(x86)/Steam/steamapps/common/Dominatrix Simulator/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.23f1 (3f4e01f1a5ec)
[Subsystems] Discovering subsystems at path C:/Program Files
(x86)/Steam/steamapps/common/Dominatrix Simulator/Dominatrix
Simulator_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1660 (ID=0x2184)
    Vendor:
    VRAM:     5991 MB
    Driver:   30.0.14.7111
Begin MonoManager ReloadAssembly
- Completed reload, in 46.640 seconds
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 15.843400 ms
SteamManager enabled.
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h
Line: 39)

**Comment by HeadphoneTaco** [comment]
@TrulyFooly Are you still having issues with the game crashing on launch?

**Comment by HeadphoneTaco** [comment]
Closing, as this issue is old, and likely resolved in newer builds
