### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by discoamazing987** [deviant-dev/dominatrix-simulator-issues#240]
I saw polish translation and there are a lot of mistakes. My native language is polish and i thought i could help.

**Comment by deviant-dev** [comment]
Hi @discoamazing987!

I'm sorry we didn't see this sooner. We'd love your help with Polish translation if you have the time! I will warn you, though: We have almost 6000 lines of dialog to translate, so it's no small feat! That's why we've had to use (terrible) automatic translation for now until we've finished the scenes.

You can see the VO translation spreadsheet here if you are interested:
https://docs.google.com/spreadsheets/d/1iTrPvIRH0BQ6VTF5brliX565xmZrPyAs0U_BsvQ6j-0/edit#gid=1080955222&fvid=865061189

A good way to reach out is through our Discord server:
https://discord.deviant.tech/

And if you are still interested, you can message me directly about it at DeviantDev#6669
